development:
  adapter: postgresql
  encoding: unicode
  database: vcruit_development
  username: louis
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: vcruit_test
  username: louis
  password:
  host: localhost
  port: 5432
	
production:
  adapter: postgresql
  database: vcruit_production
  pool: 5
  timeout: 5000